spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university-cms
    username: postgres
    password: baloo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
