spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university-cms
    username: postgres
    password: baloo
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

