spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university-cms
    username: postgres
    password: baloo
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: $2a$08$867fGGFJrP9pexF/63WNgeEOS0bzBDBbN.gSnSo9wfRP1MGUGbLMO
      roles: ADMIN
